# 水平分库示例
spring:
  shardingsphere:
    datasource:
      names: ds1,ds2
      ds1:  # 第一个数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.64.14:3307/sj-database-sharding-1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root

      ds2: # 第二个数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.64.14:3307/sj-database-sharding-2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root

    rules:       # 分片规则配置
      sharding:
        sharding-algorithms:
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{user_id % 2 + 1}
        tables:
          course:
            actual-data-nodes: ds$->{1..2}.course
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database-inline

    props:
      sql-show: true  # 显示sql日志

  main:
    allow-bean-definition-overriding: true  # 一个实体类对应两张表，覆盖



